// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.

module.exports = {
  "jam buka": "jam operasional",
  "buka jam berapa": "jam operasional",
  "jam operasional": "jam operasional",
  "jam buka toko": "jam operasional",
  "buka toko jam brp": "jam operasional",
  "lokasi toko": "lokasi",
  "toko kamu di mana": "lokasi",
  "alamat": "lokasi",
  "dimana alamat toko": "lokasi",
  "lokasi": "lokasi",
  "produk": "produk",
  "barang": "produk",
  "apa aja yang dijual": "produk",
  "barang apa saja yang ada": "produk",
  "barang apa aja": "produk",
  "harga": "harga",
  "berapa harganya": "harga",
  "harga barang ini berapa": "harga",
  "berapa harga barang ini": "harga",
  "pembayaran": "pembayaran",
  "bayar": "pembayaran",
  "metode pembayaran": "pembayaran",
  "hai kak, selamat pagi": "hai kak, selamat pagi",
  "hai": "hai",
  "hai broh": "hai broh",
  "xyxtuxyuxxy": "xyxtuxyuxxy",
  "mas pulang jam berapa": "mas pulang jam berapa"
};
